services:
  db-postgres:
    image: postgis/postgis:14-3.3
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=db_fleet_orders
    ports:
      - "5432:5432"
    volumes:
      - ./database/init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
